### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by rebaz36** [mullenlucas/todo-list#7]
Peer to Peer Code Review Session: To Do List

**Comment by Agetuni** [comment]
there are linters issues on the main branch

**Comment by rebaz36** [comment]
Great work so Far @Ukaypromise, you've done really well.

bare in mind the followings to improvise your project further to the given design

- strikethrough texts when a list is marked as completed
- implemented an event listener for the Enter Key so that you can add lists with Enter instead of only having to press the button

**Comment by Mov305** [comment]
1- Add a cursor to the pointer
2- You should exit the menu when you unfocus it 
3- you shouldn't add unnecessary buttons
